# -*- coding: utf-8 -*-
"""Project 106.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SoDilGXaK7wDSvlM5QcP9m39iukL6kXn
"""

from google.colab import files
data_to_load = files.upload()

import plotly.express as px
import csv
with open("Student Marks vs Days Present.csv")as csv_files:
  df = csv.DictReader(csv_files)
  fig = px.scatter(df,x = "Marks In Percentage",y = "Days Present")
  fig.show()

with open("cups of coffee vs hours of sleep.csv")as csv_files:
 df = csv.DictReader(csv_files)
 fig = px.scatter(df,x="Coffee in ml",y="sleep in hours")
 fig.show()

import csv
import numpy as np

def plotFigure(data_path):
    with open(data_path) as csv_file:
        df = csv.DictReader(csv_file)
        fig = px.scatter(df,x="Marks In Percentage", y="Days Present")
        fig.show()

def getDataSource(data_path):
    marks_in_percentage = []
    days_present = []
    with open(data_path) as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            marks_in_percentage.append(float(row["Marks In Percentage"]))
            days_present.append(float(row["Days Present"]))

    return {"x" : marks_in_percentage, "y": days_present}

def findCorrelation(datasource):
    correlation = np.corrcoef(datasource["x"], datasource["y"])
    print("Correlation between Days present and marks in percent :-  \n--->",correlation[0,1])

data_path  = "Student Marks vs Days Present.csv"
datasource = getDataSource(data_path)
findCorrelation(datasource)
plotFigure(data_path)

import csv
import numpy as np


def getDataSource(data_path):
    cups_of_coffee = []
    hours_of_sleep = []
    with open(data_path) as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            cups_of_coffee.append(float(row["Coffee in ml"]))
            hours_of_sleep.append(float(row["sleep in hours"]))

    return {"x" : cups_of_coffee, "y": hours_of_sleep}

def findCorrelation(datasource):
    correlation = np.corrcoef(datasource["x"], datasource["y"])
    print("Correlation between cups of coffee and hours of sleep :-  \n--->",correlation[0,1])

data_path  = "cups of coffee vs hours of sleep.csv"
datasource = getDataSource(data_path)
findCorrelation(datasource)